services:
  - type: web
    name: account
    env: docker
    repo: https://github.com/Brobot64/weverefy-backinred
    branch: master
    dockerfilePath: account/Dockerfile
    buildCommand: "cd account && npm install"
    

  - type: web
    name: identity
    env: docker
    repo: https://github.com/Brobot64/weverefy-backinred
    branch: master
    dockerfilePath: identity/Dockerfile
    buildCommand: "cd identity && npm install"
    


  - type: web
    name: gateway
    env: docker
    repo: https://github.com/Brobot64/weverefy-backinred
    branch: master
    dockerfilePath: gateway/Dockerfile
    buildCommand: "cd gateway && npm install"
    flintsa
    xhfxgdhj 

