services:
  - type: web
    name: account
    env: docker
    runtime: node
    repo: https://github.com/Brobot64/weverefy-backinred
    branch: master
    dockerfilePath: account/Dockerfile
    buildCommand: "cd account && npm install"
    # env
    

  - type: web
    name: identity
    env: docker
    runtime: node
    repo: https://github.com/Brobot64/weverefy-backinred
    branch: master
    dockerfilePath: identity/Dockerfile
    buildCommand: "npm install"
    # env
    


  - type: web
    name: gateway
    env: docker
    runtime: node
    repo: https://github.com/Brobot64/weverefy-backinred
    branch: master
    dockerfilePath: gateway/Dockerfile
    buildCommand: "cd gateway && npm install"
    # env

